name: seonbi
version: 0.1.0
synopsis: SmartyPants for Korean language
category: Text
author: Hong Minhee <hong.minhee@gmail.com>
maintainer: Hong Minhee <hong.minhee@gmail.com>
copyright: "\xa9 2018\u20132019 Hong Minhee"
license: LGPL-2.1
homepage: https://github.com/dahlia/seonbi
bug-reports: https://github.com/dahlia/seonbi/issues
git: git://github.com/dahlia/seonbi.git
description:
  Please see the README.md on GitHub at <https://github.com/dahlia/seonbi>.
extra-source-files:
- src/Text/Seonbi/Unihan/*.json
- CHANGES.md
- README.md
data-dir: data
data-files:
- '*.tsv'
build-type: Custom
custom-setup:
  dependencies:
  - base
  - bytestring
  - Cabal
  - directory >= 1 && < 2
  - filepath
  - http-client >= 0.5 && < 0.6
  - temporary >= 1.2 && < 1.4
  - text
  - zip >= 1.1 && < 1.3
dependencies:
- aeson >= 1.3.1 && < 1.5
- base >= 4.7 && < 5
- bytestring
- containers
- text
flags:
  static:
    description: Static link
    manual: true
    default: false
when:
- condition: os(darwin)
  else:
    ghc-options:
    - -Werror
    - -Wall
    - -fprint-explicit-kinds
  then:
    ghc-options:
    - -Werror
    - -Wall
    - -fprint-explicit-kinds
    - -optP-Wno-nonportable-include-path
    # The above option works around https://github.com/haskell/cabal/issues/4739
library:
  source-dirs: src
  dependencies:
  - attoparsec >= 0.12 && < 1
  - cassava >= 0.5 && < 0.6
  - data-default >= 0.2 && < 1
  - filepath >= 1 && < 2
  - file-embed >= 0.0.10 && < 0.0.12
  - text-trie >= 0.2.5 && < 0.3
executables:
  seonbi:
    main: seonbi.hs
    source-dirs: app
    dependencies:
    - cases == 0.1.3.2
    - html-charset >= 0.1 && < 0.2
    - iconv >= 0.4 && < 0.5
    - optparse-applicative >= 0.14 && < 0.15
    - seonbi
    when: &executable-ghc-options
    - condition: flag(static)
      then:
        when:
        - condition: os(darwin) || os(windows)
          then:
            ghc-options:
            - -Wall
            - -fwarn-incomplete-uni-patterns
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            # Static link
            - -static
            - -optc-Os
          else:
            ghc-options:
            - -Wall
            - -fwarn-incomplete-uni-patterns
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            # Static link
            - -static
            - -optl-static
            - -optl-pthread
            - -optc-Os
            - -fPIC
        ld-options:
        - -static
      else:
        ghc-options:
        - -Wall
        - -fwarn-incomplete-uni-patterns
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
  seonbi-api:
    main: seonbi-api.hs
    source-dirs: app
    dependencies:
    - http-types >= 0.12 && < 0.13
    - optparse-applicative >= 0.14 && < 0.15
    - seonbi
    - wai >= 3.2 && < 3.3
    - warp >= 3.2 && < 3.3
    when: *executable-ghc-options
tests:
  doctest:
    main: doctest.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    dependencies:
    - doctest
    - doctest-discover
    - QuickCheck
    - seonbi
    - unicode-show
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wno-incomplete-uni-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.4.8 && < 3
    - hspec-discover >= 2.4.8 && < 3
    - seonbi
  hlint:
    main: hlint.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    dependencies:
    - hlint >= 2.1.7 && < 2.2
