name: seonbi
version: 0.1.0
synopsis: SmartyPants for Korean language
category: Text
author: Hong Minhee <hong.minhee@gmail.com>
maintainer: Hong Minhee <hong.minhee@gmail.com>
copyright: "\xa9 2018\u20132019 Hong Minhee"
license: LGPL-2.1
homepage: https://github.com/dahlia/seonbi
bug-reports: https://github.com/dahlia/seonbi/issues
git: git://github.com/dahlia/seonbi.git
description:
  Please see the README.md on GitHub at <https://github.com/dahlia/seonbi>.
extra-source-files:
- src/Text/Seonbi/Unihan/*.json
- CHANGES.md
- README.md
data-dir: data
data-files:
- '*.tsv'
build-type: Custom
custom-setup:
  dependencies:
  - base
  - bytestring
  - Cabal
  - directory >= 1 && < 2
  - filepath
  - http-client >= 0.5 && < 0.6
  - temporary >= 1.2 && < 1.4
  - text
  - zip >= 1.1 && < 1.2
ghc-options:
- -Werror
- -Wall
- -fwarn-incomplete-uni-patterns
- -fprint-explicit-kinds
dependencies:
- aeson >= 1.3.1 && < 1.4
- base >= 4.7 && < 5
- bytestring
- containers
- text
library:
  source-dirs: src
  dependencies:
  - attoparsec >= 0.12 && < 1
  - cassava >= 0.5 && < 0.6
  - data-default >= 0.2 && < 1
  - filepath >= 1 && < 2
  - file-embed >= 0.0.10 && < 0.0.12
  - text-trie >= 0.2.5 && < 0.3
executables:
  seonbi:
    main: seonbi.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cases == 0.1.3.2
    - html-charset >= 0.1 && < 0.2
    - iconv >= 0.4 && < 0.5
    - optparse-applicative >= 0.14 && < 0.15
    - seonbi
tests:
  doctest:
    main: doctest.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    dependencies:
    - doctest
    - doctest-discover
    - QuickCheck
    - seonbi
    - unicode-show
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wno-incomplete-uni-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.4.8 && < 3
    - hspec-discover >= 2.4.8 && < 3
    - seonbi
  hlint:
    main: hlint.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    dependencies:
    - hlint >= 2.1.7 && < 2.2
