resolver: lts-13.30
packages:
- .
extra-deps:
- bytestring-trie-0.2.5.0
- html-charset-0.1.0
flags:
  seonbi:
    iconv: true
ghc-options:
  "$locals": -fhide-source-paths
require-stack-version: ">=2.1.1"
